// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Expression.proto

package len_field_based_and_protobuf_demo;

public final class ExpressionProto {
  private ExpressionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExpressionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:len_field_based_and_protobuf_demo.Expression)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 arg1 = 1;</code>
     */
    boolean hasArg1();
    /**
     * <code>required int32 arg1 = 1;</code>
     */
    int getArg1();

    /**
     * <code>required int32 arg2 = 2;</code>
     */
    boolean hasArg2();
    /**
     * <code>required int32 arg2 = 2;</code>
     */
    int getArg2();

    /**
     * <code>required string op = 3;</code>
     */
    boolean hasOp();
    /**
     * <code>required string op = 3;</code>
     */
    java.lang.String getOp();
    /**
     * <code>required string op = 3;</code>
     */
    com.google.protobuf.ByteString
        getOpBytes();
  }
  /**
   * Protobuf type {@code len_field_based_and_protobuf_demo.Expression}
   */
  public  static final class Expression extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:len_field_based_and_protobuf_demo.Expression)
      ExpressionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Expression.newBuilder() to construct.
    private Expression(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Expression() {
      arg1_ = 0;
      arg2_ = 0;
      op_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Expression(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              arg1_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              arg2_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              op_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return len_field_based_and_protobuf_demo.ExpressionProto.internal_static_len_field_based_and_protobuf_demo_Expression_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return len_field_based_and_protobuf_demo.ExpressionProto.internal_static_len_field_based_and_protobuf_demo_Expression_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              len_field_based_and_protobuf_demo.ExpressionProto.Expression.class, len_field_based_and_protobuf_demo.ExpressionProto.Expression.Builder.class);
    }

    private int bitField0_;
    public static final int ARG1_FIELD_NUMBER = 1;
    private int arg1_;
    /**
     * <code>required int32 arg1 = 1;</code>
     */
    public boolean hasArg1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 arg1 = 1;</code>
     */
    public int getArg1() {
      return arg1_;
    }

    public static final int ARG2_FIELD_NUMBER = 2;
    private int arg2_;
    /**
     * <code>required int32 arg2 = 2;</code>
     */
    public boolean hasArg2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 arg2 = 2;</code>
     */
    public int getArg2() {
      return arg2_;
    }

    public static final int OP_FIELD_NUMBER = 3;
    private volatile java.lang.Object op_;
    /**
     * <code>required string op = 3;</code>
     */
    public boolean hasOp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string op = 3;</code>
     */
    public java.lang.String getOp() {
      java.lang.Object ref = op_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          op_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string op = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOpBytes() {
      java.lang.Object ref = op_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        op_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasArg1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasArg2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, arg1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, arg2_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, op_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, arg1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, arg2_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, op_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof len_field_based_and_protobuf_demo.ExpressionProto.Expression)) {
        return super.equals(obj);
      }
      len_field_based_and_protobuf_demo.ExpressionProto.Expression other = (len_field_based_and_protobuf_demo.ExpressionProto.Expression) obj;

      boolean result = true;
      result = result && (hasArg1() == other.hasArg1());
      if (hasArg1()) {
        result = result && (getArg1()
            == other.getArg1());
      }
      result = result && (hasArg2() == other.hasArg2());
      if (hasArg2()) {
        result = result && (getArg2()
            == other.getArg2());
      }
      result = result && (hasOp() == other.hasOp());
      if (hasOp()) {
        result = result && getOp()
            .equals(other.getOp());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasArg1()) {
        hash = (37 * hash) + ARG1_FIELD_NUMBER;
        hash = (53 * hash) + getArg1();
      }
      if (hasArg2()) {
        hash = (37 * hash) + ARG2_FIELD_NUMBER;
        hash = (53 * hash) + getArg2();
      }
      if (hasOp()) {
        hash = (37 * hash) + OP_FIELD_NUMBER;
        hash = (53 * hash) + getOp().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static len_field_based_and_protobuf_demo.ExpressionProto.Expression parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static len_field_based_and_protobuf_demo.ExpressionProto.Expression parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static len_field_based_and_protobuf_demo.ExpressionProto.Expression parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static len_field_based_and_protobuf_demo.ExpressionProto.Expression parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static len_field_based_and_protobuf_demo.ExpressionProto.Expression parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static len_field_based_and_protobuf_demo.ExpressionProto.Expression parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static len_field_based_and_protobuf_demo.ExpressionProto.Expression parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static len_field_based_and_protobuf_demo.ExpressionProto.Expression parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static len_field_based_and_protobuf_demo.ExpressionProto.Expression parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static len_field_based_and_protobuf_demo.ExpressionProto.Expression parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static len_field_based_and_protobuf_demo.ExpressionProto.Expression parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static len_field_based_and_protobuf_demo.ExpressionProto.Expression parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(len_field_based_and_protobuf_demo.ExpressionProto.Expression prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code len_field_based_and_protobuf_demo.Expression}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:len_field_based_and_protobuf_demo.Expression)
        len_field_based_and_protobuf_demo.ExpressionProto.ExpressionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return len_field_based_and_protobuf_demo.ExpressionProto.internal_static_len_field_based_and_protobuf_demo_Expression_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return len_field_based_and_protobuf_demo.ExpressionProto.internal_static_len_field_based_and_protobuf_demo_Expression_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                len_field_based_and_protobuf_demo.ExpressionProto.Expression.class, len_field_based_and_protobuf_demo.ExpressionProto.Expression.Builder.class);
      }

      // Construct using len_field_based_and_protobuf_demo.ExpressionProto.Expression.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        arg1_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        arg2_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        op_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return len_field_based_and_protobuf_demo.ExpressionProto.internal_static_len_field_based_and_protobuf_demo_Expression_descriptor;
      }

      @java.lang.Override
      public len_field_based_and_protobuf_demo.ExpressionProto.Expression getDefaultInstanceForType() {
        return len_field_based_and_protobuf_demo.ExpressionProto.Expression.getDefaultInstance();
      }

      @java.lang.Override
      public len_field_based_and_protobuf_demo.ExpressionProto.Expression build() {
        len_field_based_and_protobuf_demo.ExpressionProto.Expression result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public len_field_based_and_protobuf_demo.ExpressionProto.Expression buildPartial() {
        len_field_based_and_protobuf_demo.ExpressionProto.Expression result = new len_field_based_and_protobuf_demo.ExpressionProto.Expression(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.arg1_ = arg1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.arg2_ = arg2_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.op_ = op_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof len_field_based_and_protobuf_demo.ExpressionProto.Expression) {
          return mergeFrom((len_field_based_and_protobuf_demo.ExpressionProto.Expression)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(len_field_based_and_protobuf_demo.ExpressionProto.Expression other) {
        if (other == len_field_based_and_protobuf_demo.ExpressionProto.Expression.getDefaultInstance()) return this;
        if (other.hasArg1()) {
          setArg1(other.getArg1());
        }
        if (other.hasArg2()) {
          setArg2(other.getArg2());
        }
        if (other.hasOp()) {
          bitField0_ |= 0x00000004;
          op_ = other.op_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasArg1()) {
          return false;
        }
        if (!hasArg2()) {
          return false;
        }
        if (!hasOp()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        len_field_based_and_protobuf_demo.ExpressionProto.Expression parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (len_field_based_and_protobuf_demo.ExpressionProto.Expression) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int arg1_ ;
      /**
       * <code>required int32 arg1 = 1;</code>
       */
      public boolean hasArg1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 arg1 = 1;</code>
       */
      public int getArg1() {
        return arg1_;
      }
      /**
       * <code>required int32 arg1 = 1;</code>
       */
      public Builder setArg1(int value) {
        bitField0_ |= 0x00000001;
        arg1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 arg1 = 1;</code>
       */
      public Builder clearArg1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        arg1_ = 0;
        onChanged();
        return this;
      }

      private int arg2_ ;
      /**
       * <code>required int32 arg2 = 2;</code>
       */
      public boolean hasArg2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 arg2 = 2;</code>
       */
      public int getArg2() {
        return arg2_;
      }
      /**
       * <code>required int32 arg2 = 2;</code>
       */
      public Builder setArg2(int value) {
        bitField0_ |= 0x00000002;
        arg2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 arg2 = 2;</code>
       */
      public Builder clearArg2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        arg2_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object op_ = "";
      /**
       * <code>required string op = 3;</code>
       */
      public boolean hasOp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string op = 3;</code>
       */
      public java.lang.String getOp() {
        java.lang.Object ref = op_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            op_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string op = 3;</code>
       */
      public com.google.protobuf.ByteString
          getOpBytes() {
        java.lang.Object ref = op_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          op_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string op = 3;</code>
       */
      public Builder setOp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        op_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string op = 3;</code>
       */
      public Builder clearOp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        op_ = getDefaultInstance().getOp();
        onChanged();
        return this;
      }
      /**
       * <code>required string op = 3;</code>
       */
      public Builder setOpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        op_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:len_field_based_and_protobuf_demo.Expression)
    }

    // @@protoc_insertion_point(class_scope:len_field_based_and_protobuf_demo.Expression)
    private static final len_field_based_and_protobuf_demo.ExpressionProto.Expression DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new len_field_based_and_protobuf_demo.ExpressionProto.Expression();
    }

    public static len_field_based_and_protobuf_demo.ExpressionProto.Expression getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Expression>
        PARSER = new com.google.protobuf.AbstractParser<Expression>() {
      @java.lang.Override
      public Expression parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Expression(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Expression> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Expression> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public len_field_based_and_protobuf_demo.ExpressionProto.Expression getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_len_field_based_and_protobuf_demo_Expression_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_len_field_based_and_protobuf_demo_Expression_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Expression.proto\022!len_field_based_and_" +
      "protobuf_demo\"4\n\nExpression\022\014\n\004arg1\030\001 \002(" +
      "\005\022\014\n\004arg2\030\002 \002(\005\022\n\n\002op\030\003 \002(\tB\021B\017Expressio" +
      "nProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_len_field_based_and_protobuf_demo_Expression_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_len_field_based_and_protobuf_demo_Expression_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_len_field_based_and_protobuf_demo_Expression_descriptor,
        new java.lang.String[] { "Arg1", "Arg2", "Op", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
